# FSS Starting a new project: Ethics, Data Management and Privacy {#new-rdm}

There are some things that all research at the faculty needs to comply with if you work with data from human respondents. So when starting a new project or study – or significantly updating or expanding and existing one – it’s good to check whether the following things are in order:

1. **Ethics Review:** the Research Ethics Review Committee provides a self-check that consist of a list of Yes/No questions that takes less than five minutes to complete. This scans for ethics issues, and advises on next steps. More information on Ethics Review can be found here.
2. Research Data Management (RDM): you will need to consider what you do with your research data before you collect it, because you need to tell your respondents what you’re doing with it. The faculty advises you to use Yoda for your Data Storage, Archiving and Publication. Other options are available, check out the storage finder.
3. Privacy: all data that can be linked in any way to living persons is considered personal data under GDPR. For most researchers this means:
	- You must take appropriate technical and organization measures to secure data. For most data (including sensitive data, such as data on health, sexual preferences, political opinions etc.), Yoda and VU-managed devices offer sufficient protection. If you have sensitive data and want to use other storage solutions, it’s best to check in with the Data Steward or RDM Support Desk to find what would work best for your needs.
	-You should ensure that you have unambiguous informed consent of your research participants. Note that informed really means informed: you have to provide your participants with information about what you will do with the data, and what their rights are and how to excercise them. You can do this by having your respondents sign an informed consent sheet based on the faculty template (Dutch), or provide them with (a link to) a privacy statement based on the VU template (Dutch) and ask them if they’ve read it and accept it.
	-If you cannot obtain consent, you should contact your Data Steward to see how you can still legally work with your data.
	-You must ensure that all data processing activities (collection, analysis, publishing, archiving, etc.) are entered in the VU’s central data processing registry. Currently, DMPs created using the VU template in DMP Online are linked automatically to this registry, meaning the researcher does not need to take additional action for this. If you don’t have DMP on DMP Online, there is a short form available on DMP Online that you can use to just enter the legally required information.
	-If personal data is handled by third parties (e.g. a survey firm or data collection platform), you should contact the Data Steward to help you get the proper agreements in place to do this securely, for example Data Processing Agreements. The VU has these agreements in place with VU-provided tools such as Yoda and Qualtrics. The Data Steward is there to help you with templates and getting legal advice for getting these agreements with other service providers and partners.
4. Data Management Plan (DMP): all data collection done at the faculty should be covered by a Data Managment Plan (DMP). So once you have given all of the above some thought, you should start writing one, or adapt an existing one, by going to DMP Online. DMPs are living documents: you are encouraged to change them if what you plan to do with the data changes. Ideally, you make your DMPs public on DMP Online, so your colleagues can easily learn from all the hard work you put into steps 1-3.

## Getting support

You can get support and find more information in the following places:

    The [Faculty Data Steward][datasteward] (or the [RDM Support Desk][rdmsupport] in case you can’t reach the data steward)
    The [Faculty RDM Page][fss-rdm-info] (which includes links to templates of informed consent letters, a FAQ, and content you can use for proposals etc.)
    The [Research Data Support Portal][rds-portal] (which contains links to all other VU-wide support there is on RDM)
    The [RDM Libguides][libguide]. 
