# RDM: An FSS Guide to FAIR Data {#rdm-fair}

The [FAIR principles](https://www.nature.com/articles/sdata201618) are a set of principles that guide researchers in making their data (or other research outputs) more valuable by increasing visibility, fostering collaboration, facilitating co-creation, and promoting transparency. To effectively implement the FAIR principles, it is beneficial to envision how your data will be reused, and then apply each principle accordingly. This involves ensuring discoverability of your data by end users, enabling easy access, facilitating integration with existing knowledge and workflows, and promoting its reuse.

Given the diverse research traditions and approaches to data reuse within the faculty, there isn't a universally prescribed approach for applying the FAIR principles. However, as a minimum requirement, all data utilized within FSS should be usable for verifying the findings presented in publications resulting from the data. This article provides practical pointers, aligned with the FAIR principles, on how you can make verification possible. Additionally, it presents further steps you can take to increase the impact of your research outputs.

## Findable

Findable means people can find out about the existence of your dataset, and know where to find more information about it.

Actions required to allow for verification:

- Register your data set in a registry like the VU Research Portal. (NB: you don't need to upload your data set for this!)
- Ensure your data set is assigned a DOI (for example by adding it to a Vault on Yoda and publishing the metadata).

More actions you can take to make your data set more Findable:

- Cite your data sets in your paper.


## Accessible

Accessible means that there should be an established way to access your data. This does not mean your data should be public, just that there is a clearly communicated and transparent procedure put in place to access the data. 

Actions required to allow for verification:

- Add a data availability statement in your publication that explains how, and under what conditions, the data can be accessed.
- Archive your data in a restricted-access repository like Yoda. 

More actions you can take to make your data set more Accessible:

- Make your data publicly available on Yoda, the OSF or DataVerseNL.

## Inter-operable

Inter-operable means that someone else can use your data and combine it with their existing knowledge and workflows.

Actions required by to allow for verification:

- Use common, preferably open, file formats.
- Include documentation that can help people make sense of your data, such as codebooks, interviewer manuals, and topic lists. 
- Wherever possible, use a language that can be understood by anyone who may reasonably be expected to use your data.

More actions you can take to make your data set more Inter-operable:

- Use standardized variables, coding schemes and vocabularies.
- Make sure the metadata of your datasets link to related datasets, publications and other relevant research outputs.

## Re-usable

For your data to be re-usable, it needs to be clear what can and cannot happen with your data.

Actions required to allow for verification:

- Include the informed consent sheets or privacy statements you provided your respondents, so that it is clear what they allow the data to be used for.
- Make sure that when you register your dataset, or deposit it into a repository, you include detailed information like author, topic, keywords, etc. See the [VU's minimal metadata standards](https://github.com/vu-rdm-tech/metadata/blob/main/minimal_metadata_guide.md).

Actions you can take to make your data more Re-usable:

- Include detailed information, for example in a readme, on the provenance of your data: where it comes from, how was it has been collected and how it was processed.
- Include a license, like CC-BY or the DANS license, with your data; or set out a Data Sharing Agreement that exactly states what a recipient can do with the data.




